[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Memory & Partition Settings
board_build.partitions = huge_app.csv
board_upload.flash_size = 4MB

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DDEBUG_VERBOSE=0

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    links2004/WebSockets @ ^2.4.1
    olikraus/U8g2 @ ^2.35.9
    adafruit/Adafruit NeoPixel @ ^1.12.0
    madhephaestus/ESP32Servo @ ^1.2.1
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    adafruit/RTClib @ ^2.1.4